### ISSUE TITLE
Versioning strategy, towards a v1.0 tool

### ISSUE THREAD

**Issue by sadielbartholomew** [GreenScheduler/cats#29]
Here and within the next meeting we should discuss versioning and how we want to approach it, in particular:

* at what stage we can consider we have a version '1.0' package of `cats`, including alpha and/or beta candidates towards that;
* what system is best to use for the versioning going forward, e.g. semantic, date-based, etc.

So it would be a good idea to try to think a bit about this in advance.

**Comment by sadielbartholomew** [comment]
With regards to:

> developer docs (python style guide? black?)

I was just thinking it would be nice to configure and apply such code formatting such as `black` (which would be my choice, too) ASAP because the codebase is a bit unwieldy to work with at the moment due to the long line lengths in particular, and because `black`-ifying the codebase can be done very quickly with the command.

Maybe someone can set up some pre-commits to apply `black` and some other auto-formatters and -checkers (I like to use `isort` and `flake8` also, personally) and update the codebase for formatting in line with those? Happy to do that myself if there is consensus (should be able to find some time later in the week)?

**Comment by abhidg** [comment]
Separate issues made, closing this. v1 tasks are being tracked in https://github.com/GreenScheduler/cats/milestone/1
