### ISSUE TITLE
Calculate corresponding carbon footprints

### ISSUE THREAD

**Issue by Llannelongue** [GreenScheduler/cats#3]

**Comment by colinsauze** [comment]
I think we still need to do some further integration and testing around this one. Did we ever complete the mechanism to get the data from the scheduler to the carbon footprint calculator? Do we still need a way to capture information about job memory and compute requirements?

**Comment by Llannelongue** [comment]
Yes part of the code was last-minute demo-only fixes, so now that we have time it would be good to integrate it neatly. @tlestang did wonders yesterday, so I can liaise with him, and I'll also clean up my code on carbon footprint calculation

**Comment by tlestang** [comment]
hey - #20 is now ready for review. Its a first implementation of footprint calculation and display given machine and job info.

**Comment by tlestang** [comment]
Although one important missing piece is that best and average carbon intensity are still harcoded and should ultimately be returned by `cats` internals alongside the start time (I think?)

**Comment by tlestang** [comment]
Closed by #52
