### ISSUE TITLE
Deploy the documentation site via a GitHub Action

### ISSUE THREAD

**Issue by sadielbartholomew** [GreenScheduler/cats#48]
A follow-on from #47, add a GitHub Action workflow to generate and host via GitHub Pages the built Sphinx documentation pages from the source `.rst` content.

As part of this Issue, the following should be completed:
- [x] Add a GitHub Action workflow to deploy the built docs site to GitHub Pages.
- [x] Set the workflow job to run to generate those pages (checking they all render and link as they should).
- [x] Configure GitHub Pages via 'Settings' on the repo to host the generated pages as a site.
- [x] Update ['LINK-PENDING' in the README in the first sentence under the 'Documentation' heading](https://github.com/GreenScheduler/cats#documentation) to point to the link of the landing/index page of the new hosted docs.
- [x] Update the repository webpage link (currently not specified) to be the link to the landing/index page of the new hosted docs.

If anyone wants to take this on, please feel free and if so, 'assign' yourself here so we know you are working on it. I can do it, but it might be some weeks before I get round to it, so until the point then when I assign myself, I won't be working on it. (And of course I'm happy to provide any guidance relating to the content and infrastructure I added in #47 towards getting this done.)

#### Essential info.

The documentation source including confirguration and makefile (etc.) is all contained under the `docs/` repository. The README document in that directory explains the build process via the core command `make html`, which is what we need to automate via the Actions workflow.

**Comment by tlestang** [comment]
Merged #51 in

**Comment by ljcolling** [comment]
Is it ok to close this now @tlestang and @sadielbartholomew... all the tasks are now completed

**Comment by sadielbartholomew** [comment]
Fantastic stuff. Agreed, we can close, though note the follow-on issue I am putting up relating to the API reference...
