### ISSUE TITLE
Wrap schedulers, starting with at(1)

### ISSUE THREAD

**Issue by andreww** [GreenScheduler/cats#53]
In the current design we use `cats` to generate some output (on standard out) that can be used as an argument to `at` to set the runtime. All other output goes to standard error. This makes handling out output a bit complicated and cats does not really look like a stand alone scheduler.

One option would be to rebuild the command line interface to `cats` such that it looks like a scheduler itself and under the hood calls `at` having done the calculation for the start time. This would probably use processing from the standard library. It could also open the door to letting us ship more than one command line programme.

Anyhow, this came up in #52 and it seems like it needs thinking about.

**Comment by andreww** [comment]
Love the idea of making other schedulers configurable. And yes - an option to generate json encoded information could be very useful for interoperability. I also imagine an API in python-land would be useful for some. Would we want a single command line programme to do everything or more simpler programmes?

**Comment by colinsauze** [comment]
Something I've been wondering, what other schedulers can directly use our current output format without any additional parsing? If we wanted to use Cats inside a cron job as it currently stands, I think I'd probably create a cron script to start at the earliest possible time to run the job and then have that invoke at to delay the start based on the Cats output.

**Comment by andreww** [comment]
So we don't loose the idea, @abhidg suggested:

> A simple way to “schedule” could be by using the —begin flag in sbatch: https://slurm.schedmd.com/sbatch.html#OPT_begin
> This of course doesn’t guarantee that the job will start then, as the maximum number of jobs might be running already. On a fairly empty queue, this might be a good approximation.

From a quick look at that link, I think we have all the information we need to enable this using the same approach as we use for `at` at the moment, but we probably need a different time output format. If I'm correct, we would need a new command line argument for this too.
