### ISSUE TITLE
Setup CI testing

### ISSUE THREAD

**Issue by andreww** [GreenScheduler/cats#6]
Once we have a test or two committed we should turn on testing. We may want to be clever about how we do this to minimise the carbon use of our tests and use this as an example for the turing way book chapter (see #4).

**Comment by andreww** [comment]
Minimise carbon overhead https://github.com/marketplace/actions/pytest-last-failed

**Comment by colinsauze** [comment]
We agreed to test against Python 3.8 and 3.11.

**Comment by colinsauze** [comment]
turn on black checking too

**Comment by colinsauze** [comment]
basic CI testing is now setup, we might benefit from some more extensive testing though. But closing this issue as CI is now in place.
