### ISSUE TITLE
Increase test coverage

### ISSUE THREAD

**Issue by abhidg** [GreenScheduler/cats#74]
Get coverage as close to 100% before v1 release

**Comment by tlestang** [comment]
Any area in particular your are working on? I was considering spending some time on testing the carbon footprint estimation but I wouldn't want to step on your toes.

**Comment by abhidg** [comment]
Su

**Comment by andreww** [comment]
Probably useful for the CI to report coverage - I've added this (in the simplest way) to #82.

**Comment by abhidg** [comment]
Coverage is ~90%, will try to increase before v1, but not considering a blocker
