### ISSUE TITLE
unknown fail

### ISSUE THREAD

**Issue by mkbane** [GreenScheduler/cats#81]
falls over on first try:
INSTALL via
pip install git+https://github.com/GreenScheduler/catsthub.com/GreenScheduler/cats

but...
$ ~/.local/bin/cats -d 10
WARNING:root:config file not found
WARNING:root:Unspecified carbon intensity forecast service, using carbonintensity.org.uk
WARNING:root:location not provided. Estimating location from IP address: M3.
Traceback (most recent call last):
  File "/home/staff/banem/.local/bin/cats", line 8, in <module>
    sys.exit(main())
  File "/home/staff/banem/.local/lib/python3.9/site-packages/cats/__init__.py", line 218, in main
    config, CI_API_interface, location, duration = get_runtime_config(args)
ValueError: too many values to unpack (expected 4)

wich doesn't mean much to me! There are WARNINGs (not ERRORs) but then some unclear "ValueError" failure...

**Comment by andreww** [comment]
Thanks for the report. I think this is because we've broken things with the latest commit on our main branch on github (see #83, we're still hacking away quite hard on this project). It shouldn't take too long to fix.

**Comment by tlestang** [comment]
@mkbane This should have been fixed now that #80 is merged. Reopen if not!
