### ISSUE TITLE
Needs a manual/info page

### ISSUE THREAD

**Issue by mkbane** [GreenScheduler/cats#91]
It would aid greatly if (e.g.) "cats -h" gave a full list of each parameter and its meaning. 
(e.g. what is -c COMMAND for? how would I find that out from the command line?)

NB I cannot see in https://greenscheduler.github.io/cats/quickstart.html#basic-usage where "-c COMMAND" is discussed

Although there is useful info in https://github.com/GreenScheduler/cats/blob/main/cats/__init__.py I do not get this displayed:

mkb@deb12:~/src/mmu-linux/mmu-bin$ ~/.local/bin/cats 
usage: cats [-h] -d DURATION [-s {at}] [-a API] [-c COMMAND] [--dateformat DATEFORMAT] [-l LOCATION] [--config CONFIG] [--profile PROFILE] [--format {json}] [-f] [--cpu CPU] [--gpu GPU]
            [--memory MEMORY]
cats: error: the following arguments are required: -d/--duration

**Comment by abhidg** [comment]
`cats -h` now shows info in a better format, could you try this out? The CLI reference online is at https://greenscheduler.github.io/cats/cli-reference.html, will link to it from the Quickstart
