### ISSUE TITLE
request: output CI of suggested time period/s

### ISSUE THREAD

**Issue by mkbane** [GreenScheduler/cats#92]
Useful to have CATS say when CI is lowest (over 48h forecast) but it would also be useful to have CATS state what that value is. Then, for example, I can take my known energy to solution and directly calculated the CO2eq (rather than have to set up a config file and use an average power which is very approximate). Ta, M

**Comment by abhidg** [comment]
@mkbane Passing `--format=json` makes CATS output the value, e.g. with `cats -d 5 --loc OX1 --format=json` I get

```json
{
  "carbonIntensityNow": {
    "end": "2024-04-22T20:59:03.888682+01:00",
    "start": "2024-04-22T20:54:03.888682+01:00",
    "value": 299.8854937122222
  },
  "carbonIntensityOptimal": {
    "end": "2024-04-24T11:59:03.888682+01:00",
    "start": "2024-04-24T11:54:03.888682+01:00",
    "value": 116.0
  },
  "countryISO3": "GBR",
  "emmissionEstimate": null,
  "location": "OX1"
}
```

**Comment by mkbane** [comment]
Hi, useful to know (but needs documenting?)

Can we amend the schema to include units too? CI of 299.9 or 116.0 needs to be g CO2eq/kWh (for example) just in case anybody thought it might be kg CO2eq/kWh (or even lbs CO2eq/kWh which I’ve seen in some US literature!)

for the final field note that there’s a typo in spelling of “emission”

Yours, m
